#!/usr/bin/env bash

# Helper to determine if there are any doc changes based on the git diff:
# 
# ./contains_doc_changes.sh
# if [ $? -ne 0 ]; then
#   echo "has changes!"
# fi

IFS=$'\n'
for line in $(git diff -U0 | grep '^[+-]' | grep -Ev '^(--- a/|\+\+\+ b/)'); do
  if [[ $line != *"Auto generated by spf13/cobra on "* ]]; then
    echo "exit with 1"
    exit 1
  fi
done

exit 0
